#!/bin/sh
#
# BEFORE: DAEMON
# PROVIDE: runonboot

. /etc/rc.subr

name=runoboot
start_cmd=runonboot_setup

runonboot_setup() {

/usr/bin/stdbuf -i0 -o0 -e0 /sbin/ping 192.168.1.254 > /root/pinglog &

}

run_rc_command "$1"
